// Code generated by hj1239 gen; DO NOT EDIT.

package model

import (
	"encoding/binary"
	"fmt"
)

// MarshalBinary encodes AlarmInfoCode to binary format (GB1239)
func (m *AlarmInfoCode) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	copy(buf[pos:pos+6], m.DataTime.Bytes())
	pos += 6

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.SerialNum)
	pos += 2

	buf[pos] = m.AlarmCount
	pos++

	// TODO: encode Alarms (type []Alarm)

	return buf, nil
}

// UnmarshalBinary decodes AlarmInfoCode from binary format (GB1239)
func (m *AlarmInfoCode) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+6 > len(data) { return fmt.Errorf("%s: short read", "DataTime") }
	m.DataTime, _ = ParseGB1239Time(data[pos:pos+6])
	pos += 6

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "SerialNum") }
	m.SerialNum = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "AlarmCount") }
	m.AlarmCount = data[pos]
	pos++

	// TODO: decode Alarms (type []Alarm)

	return nil
}
// MarshalBinary encodes Alarm to binary format (GB1239)
func (m *Alarm) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	buf[pos] = m.AlarmType
	pos++

	copy(buf[pos:pos+6], m.AlarmTime.Bytes())
	pos += 6

	copy(buf[pos:], m.AlarmData)
	pos += len(m.AlarmData)

	return buf, nil
}

// UnmarshalBinary decodes Alarm from binary format (GB1239)
func (m *Alarm) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "AlarmType") }
	m.AlarmType = data[pos]
	pos++

	if pos+6 > len(data) { return fmt.Errorf("%s: short read", "AlarmTime") }
	m.AlarmTime, _ = ParseGB1239Time(data[pos:pos+6])
	pos += 6

	m.AlarmData = make([]byte, len(data)-pos)
	copy(m.AlarmData, data[pos:])
	pos = len(data)

	return nil
}
