// Code generated by hj1239 gen; DO NOT EDIT.

package model

import (
	"encoding/binary"
	"fmt"
)

// MarshalBinary encodes SupplementaryVehicleInfo to binary format (GB1239)
func (m *SupplementaryVehicleInfo) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	m.TorqueMode.PutUint8(buf[pos:pos+1])
	pos++

	m.AccelPedal.PutUint8(buf[pos:pos+1])
	pos++

	m.CumulativeFuel.PutUint32(buf[pos:pos+4], true)
	pos += 4

	m.EngineOilTemp.PutInt8(buf[pos:pos+1])
	pos++

	m.ActualFuelRate.PutUint32(buf[pos:pos+4], true)
	pos += 4

	m.CumulativeFuelUsed.PutUint32(buf[pos:pos+4], true)
	pos += 4

	m.DPFUpstreamTemp.PutInt16(buf[pos:pos+2], true)
	pos += 2

	return buf, nil
}

// UnmarshalBinary decodes SupplementaryVehicleInfo from binary format (GB1239)
func (m *SupplementaryVehicleInfo) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "TorqueMode") }
	m.TorqueMode.DecodeUint8(data[pos:pos+1])
	pos++

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "AccelPedal") }
	m.AccelPedal.DecodeUint8(data[pos:pos+1])
	pos++

	if pos+4 > len(data) { return fmt.Errorf("%s: short read", "CumulativeFuel") }
	m.CumulativeFuel.DecodeUint32(data[pos:pos+4], true)
	pos += 4

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "EngineOilTemp") }
	m.EngineOilTemp.DecodeInt8(data[pos:pos+1])
	pos++

	if pos+4 > len(data) { return fmt.Errorf("%s: short read", "ActualFuelRate") }
	m.ActualFuelRate.DecodeUint32(data[pos:pos+4], true)
	pos += 4

	if pos+4 > len(data) { return fmt.Errorf("%s: short read", "CumulativeFuelUsed") }
	m.CumulativeFuelUsed.DecodeUint32(data[pos:pos+4], true)
	pos += 4

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "DPFUpstreamTemp") }
	m.DPFUpstreamTemp.DecodeInt16(data[pos:pos+2], true)
	pos += 2

	return nil
}
// MarshalBinary encodes AnnexBData to binary format (GB1239)
func (m *AnnexBData) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	buf[pos] = m.TorqueMode
	pos++

	buf[pos] = m.AccelPedalRaw
	pos++

	binary.BigEndian.PutUint32(buf[pos:pos+4], m.CumulativeFuelRaw)
	pos += 4

	buf[pos] = m.EngineOilTempRaw
	pos++

	binary.BigEndian.PutUint32(buf[pos:pos+4], m.ActualFuelRateRaw)
	pos += 4

	binary.BigEndian.PutUint32(buf[pos:pos+4], m.CumFuelUsedRaw)
	pos += 4

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.DPFUpTempRaw)
	pos += 2

	return buf, nil
}

// UnmarshalBinary decodes AnnexBData from binary format (GB1239)
func (m *AnnexBData) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "TorqueMode") }
	m.TorqueMode = data[pos]
	pos++

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "AccelPedalRaw") }
	m.AccelPedalRaw = data[pos]
	pos++

	if pos+4 > len(data) { return fmt.Errorf("%s: short read", "CumulativeFuelRaw") }
	m.CumulativeFuelRaw = binary.BigEndian.Uint32(data[pos:pos+4])
	pos += 4

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "EngineOilTempRaw") }
	m.EngineOilTempRaw = data[pos]
	pos++

	if pos+4 > len(data) { return fmt.Errorf("%s: short read", "ActualFuelRateRaw") }
	m.ActualFuelRateRaw = binary.BigEndian.Uint32(data[pos:pos+4])
	pos += 4

	if pos+4 > len(data) { return fmt.Errorf("%s: short read", "CumFuelUsedRaw") }
	m.CumFuelUsedRaw = binary.BigEndian.Uint32(data[pos:pos+4])
	pos += 4

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "DPFUpTempRaw") }
	m.DPFUpTempRaw = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	return nil
}
