// Code generated by hj1239 gen; DO NOT EDIT.

package model

import (
	"encoding/binary"
	"fmt"
)

// MarshalBinary encodes ControlCode to binary format (GB1239)
func (m *ControlCode) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	buf[pos] = m.ControlType
	pos++

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.SerialNum)
	pos += 2

	buf[pos] = m.ParamCount
	pos++

	// TODO: encode Params (type []ControlParam)

	return buf, nil
}

// UnmarshalBinary decodes ControlCode from binary format (GB1239)
func (m *ControlCode) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "ControlType") }
	m.ControlType = data[pos]
	pos++

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "SerialNum") }
	m.SerialNum = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "ParamCount") }
	m.ParamCount = data[pos]
	pos++

	// TODO: decode Params (type []ControlParam)

	return nil
}
// MarshalBinary encodes ControlParam to binary format (GB1239)
func (m *ControlParam) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.ParamID)
	pos += 2

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.ParamLen)
	pos += 2

	copy(buf[pos:], m.ParamValue)
	pos += len(m.ParamValue)

	return buf, nil
}

// UnmarshalBinary decodes ControlParam from binary format (GB1239)
func (m *ControlParam) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "ParamID") }
	m.ParamID = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "ParamLen") }
	m.ParamLen = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	m.ParamValue = make([]byte, len(data)-pos)
	copy(m.ParamValue, data[pos:])
	pos = len(data)

	return nil
}
// MarshalBinary encodes ControlResponseCode to binary format (GB1239)
func (m *ControlResponseCode) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.SerialNum)
	pos += 2

	buf[pos] = m.ControlType
	pos++

	buf[pos] = m.Result
	pos++

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.DataLen)
	pos += 2

	copy(buf[pos:], m.Data)
	pos += len(m.Data)

	return buf, nil
}

// UnmarshalBinary decodes ControlResponseCode from binary format (GB1239)
func (m *ControlResponseCode) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "SerialNum") }
	m.SerialNum = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "ControlType") }
	m.ControlType = data[pos]
	pos++

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "Result") }
	m.Result = data[pos]
	pos++

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "DataLen") }
	m.DataLen = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	m.Data = make([]byte, len(data)-pos)
	copy(m.Data, data[pos:])
	pos = len(data)

	return nil
}
