// Code generated by hj1239 gen; DO NOT EDIT.

package model

import (
	"encoding/binary"
	"fmt"
)

// MarshalBinary encodes FileUploadNotificationCode to binary format (GB1239)
func (m *FileUploadNotificationCode) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	buf[pos] = m.FileNameLen
	pos++

	copy(buf[pos:], m.FileName)
	pos += len(m.FileName)

	binary.BigEndian.PutUint32(buf[pos:pos+4], m.FileSize)
	pos += 4

	// TODO: encode FileMD5 (type [*ast.BasicLit]byte)

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.TotalBlocks)
	pos += 2

	return buf, nil
}

// UnmarshalBinary decodes FileUploadNotificationCode from binary format (GB1239)
func (m *FileUploadNotificationCode) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "FileNameLen") }
	m.FileNameLen = data[pos]
	pos++

	m.FileName = make([]byte, len(data)-pos)
	copy(m.FileName, data[pos:])
	pos = len(data)

	if pos+4 > len(data) { return fmt.Errorf("%s: short read", "FileSize") }
	m.FileSize = binary.BigEndian.Uint32(data[pos:pos+4])
	pos += 4

	// TODO: decode FileMD5 (type [*ast.BasicLit]byte)

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "TotalBlocks") }
	m.TotalBlocks = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	return nil
}
// MarshalBinary encodes FileDataBlockCode to binary format (GB1239)
func (m *FileDataBlockCode) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.BlockIndex)
	pos += 2

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.BlockLen)
	pos += 2

	copy(buf[pos:], m.BlockData)
	pos += len(m.BlockData)

	return buf, nil
}

// UnmarshalBinary decodes FileDataBlockCode from binary format (GB1239)
func (m *FileDataBlockCode) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "BlockIndex") }
	m.BlockIndex = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "BlockLen") }
	m.BlockLen = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	m.BlockData = make([]byte, len(data)-pos)
	copy(m.BlockData, data[pos:])
	pos = len(data)

	return nil
}
// MarshalBinary encodes FileUploadCompleteCode to binary format (GB1239)
func (m *FileUploadCompleteCode) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	buf[pos] = m.Result
	pos++

	copy(buf[pos:], m.BlockMask)
	pos += len(m.BlockMask)

	return buf, nil
}

// UnmarshalBinary decodes FileUploadCompleteCode from binary format (GB1239)
func (m *FileUploadCompleteCode) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "Result") }
	m.Result = data[pos]
	pos++

	m.BlockMask = make([]byte, len(data)-pos)
	copy(m.BlockMask, data[pos:])
	pos = len(data)

	return nil
}
