// Code generated by hj1239 gen; DO NOT EDIT.

package model

import (
	"encoding/binary"
	"fmt"
)

// MarshalBinary encodes HistoricalInfoBlock to binary format (GB1239)
func (m *HistoricalInfoBlock) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	copy(buf[pos:pos+6], m.BeginTime.Bytes())
	pos += 6

	copy(buf[pos:pos+6], m.EndTime.Bytes())
	pos += 6

	copy(buf[pos:], m.Data)
	pos += len(m.Data)

	return buf, nil
}

// UnmarshalBinary decodes HistoricalInfoBlock from binary format (GB1239)
func (m *HistoricalInfoBlock) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+6 > len(data) { return fmt.Errorf("%s: short read", "BeginTime") }
	m.BeginTime, _ = ParseGB1239Time(data[pos:pos+6])
	pos += 6

	if pos+6 > len(data) { return fmt.Errorf("%s: short read", "EndTime") }
	m.EndTime, _ = ParseGB1239Time(data[pos:pos+6])
	pos += 6

	m.Data = make([]byte, len(data)-pos)
	copy(m.Data, data[pos:])
	pos = len(data)

	return nil
}
// MarshalBinary encodes HistoricalInfoCode to binary format (GB1239)
func (m *HistoricalInfoCode) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	copy(buf[pos:pos+6], m.DataTime.Bytes())
	pos += 6

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.SerialNum)
	pos += 2

	// TODO: encode Blocks (type []HistoricalInfoBlock)

	return buf, nil
}

// UnmarshalBinary decodes HistoricalInfoCode from binary format (GB1239)
func (m *HistoricalInfoCode) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+6 > len(data) { return fmt.Errorf("%s: short read", "DataTime") }
	m.DataTime, _ = ParseGB1239Time(data[pos:pos+6])
	pos += 6

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "SerialNum") }
	m.SerialNum = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	// TODO: decode Blocks (type []HistoricalInfoBlock)

	return nil
}
