// Code generated by hj1239 gen; DO NOT EDIT.

package model

import (
	"encoding/binary"
	"fmt"
)

// MarshalBinary encodes PlatformPacket to binary format (GB1239)
func (m *PlatformPacket) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	copy(buf[pos:pos+2], []byte(m.StartMarker))
	pos += 2

	buf[pos] = m.CommandFlag
	pos++

	buf[pos] = m.ResponseFlag
	pos++

	copy(buf[pos:pos+17], []byte(m.VIN))
	pos += 17

	buf[pos] = m.EncryptMode
	pos++

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.DataLength)
	pos += 2

	copy(buf[pos:], m.DataUnit)
	pos += len(m.DataUnit)

	buf[pos] = m.Checksum
	pos++

	return buf, nil
}

// UnmarshalBinary decodes PlatformPacket from binary format (GB1239)
func (m *PlatformPacket) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "StartMarker") }
	m.StartMarker = string(data[pos:pos+2])
	pos += 2

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "CommandFlag") }
	m.CommandFlag = data[pos]
	pos++

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "ResponseFlag") }
	m.ResponseFlag = data[pos]
	pos++

	if pos+17 > len(data) { return fmt.Errorf("%s: short read", "VIN") }
	m.VIN = string(data[pos:pos+17])
	pos += 17

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "EncryptMode") }
	m.EncryptMode = data[pos]
	pos++

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "DataLength") }
	m.DataLength = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	m.DataUnit = make([]byte, len(data)-pos)
	copy(m.DataUnit, data[pos:])
	pos = len(data)

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "Checksum") }
	m.Checksum = data[pos]
	pos++

	return nil
}
// MarshalBinary encodes PlatformLoginCode to binary format (GB1239)
func (m *PlatformLoginCode) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	copy(buf[pos:pos+6], m.AccessTime.Bytes())
	pos += 6

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.SerialNum)
	pos += 2

	copy(buf[pos:pos+12], []byte(m.Username))
	pos += 12

	copy(buf[pos:pos+20], []byte(m.Password))
	pos += 20

	buf[pos] = m.EncryptMode
	pos++

	return buf, nil
}

// UnmarshalBinary decodes PlatformLoginCode from binary format (GB1239)
func (m *PlatformLoginCode) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+6 > len(data) { return fmt.Errorf("%s: short read", "AccessTime") }
	m.AccessTime, _ = ParseGB1239Time(data[pos:pos+6])
	pos += 6

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "SerialNum") }
	m.SerialNum = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	if pos+12 > len(data) { return fmt.Errorf("%s: short read", "Username") }
	m.Username = string(data[pos:pos+12])
	pos += 12

	if pos+20 > len(data) { return fmt.Errorf("%s: short read", "Password") }
	m.Password = string(data[pos:pos+20])
	pos += 20

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "EncryptMode") }
	m.EncryptMode = data[pos]
	pos++

	return nil
}
// MarshalBinary encodes PlatformLogoutCode to binary format (GB1239)
func (m *PlatformLogoutCode) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	copy(buf[pos:pos+6], m.LogoutTime.Bytes())
	pos += 6

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.SerialNum)
	pos += 2

	return buf, nil
}

// UnmarshalBinary decodes PlatformLogoutCode from binary format (GB1239)
func (m *PlatformLogoutCode) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+6 > len(data) { return fmt.Errorf("%s: short read", "LogoutTime") }
	m.LogoutTime, _ = ParseGB1239Time(data[pos:pos+6])
	pos += 6

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "SerialNum") }
	m.SerialNum = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	return nil
}
// MarshalBinary encodes KeyExchangeCode to binary format (GB1239)
func (m *KeyExchangeCode) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	buf[pos] = m.KeyType
	pos++

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.KeyLength)
	pos += 2

	copy(buf[pos:], m.KeyData)
	pos += len(m.KeyData)

	copy(buf[pos:pos+6], m.EffectiveTime.Bytes())
	pos += 6

	copy(buf[pos:pos+6], m.ExpiryTime.Bytes())
	pos += 6

	return buf, nil
}

// UnmarshalBinary decodes KeyExchangeCode from binary format (GB1239)
func (m *KeyExchangeCode) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "KeyType") }
	m.KeyType = data[pos]
	pos++

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "KeyLength") }
	m.KeyLength = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	m.KeyData = make([]byte, len(data)-pos)
	copy(m.KeyData, data[pos:])
	pos = len(data)

	if pos+6 > len(data) { return fmt.Errorf("%s: short read", "EffectiveTime") }
	m.EffectiveTime, _ = ParseGB1239Time(data[pos:pos+6])
	pos += 6

	if pos+6 > len(data) { return fmt.Errorf("%s: short read", "ExpiryTime") }
	m.ExpiryTime, _ = ParseGB1239Time(data[pos:pos+6])
	pos += 6

	return nil
}
