// Code generated by hj1239 gen; DO NOT EDIT.

package model

import (
	"encoding/binary"
	"fmt"
)

// MarshalBinary encodes VehicleLoginCode to binary format (GB1239)
func (m *VehicleLoginCode) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	copy(buf[pos:pos+6], m.Time.Bytes())
	pos += 6

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.SerialNum)
	pos += 2

	copy(buf[pos:pos+20], []byte(m.ICCID))
	pos += 20

	buf[pos] = m.AuthCount
	pos++

	copy(buf[pos:], m.AuthData)
	pos += len(m.AuthData)

	copy(buf[pos:pos+6], m.LoginTime.Bytes())
	pos += 6

	return buf, nil
}

// UnmarshalBinary decodes VehicleLoginCode from binary format (GB1239)
func (m *VehicleLoginCode) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+6 > len(data) { return fmt.Errorf("%s: short read", "Time") }
	m.Time, _ = ParseGB1239Time(data[pos:pos+6])
	pos += 6

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "SerialNum") }
	m.SerialNum = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	if pos+20 > len(data) { return fmt.Errorf("%s: short read", "ICCID") }
	m.ICCID = string(data[pos:pos+20])
	pos += 20

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "AuthCount") }
	m.AuthCount = data[pos]
	pos++

	m.AuthData = make([]byte, len(data)-pos)
	copy(m.AuthData, data[pos:])
	pos = len(data)

	if pos+6 > len(data) { return fmt.Errorf("%s: short read", "LoginTime") }
	m.LoginTime, _ = ParseGB1239Time(data[pos:pos+6])
	pos += 6

	return nil
}
// MarshalBinary encodes VehicleLogoutCode to binary format (GB1239)
func (m *VehicleLogoutCode) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	copy(buf[pos:pos+6], m.Time.Bytes())
	pos += 6

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.SerialNum)
	pos += 2

	return buf, nil
}

// UnmarshalBinary decodes VehicleLogoutCode from binary format (GB1239)
func (m *VehicleLogoutCode) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+6 > len(data) { return fmt.Errorf("%s: short read", "Time") }
	m.Time, _ = ParseGB1239Time(data[pos:pos+6])
	pos += 6

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "SerialNum") }
	m.SerialNum = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	return nil
}
// MarshalBinary encodes TerminalTimeCalibrationCode to binary format (GB1239)
func (m *TerminalTimeCalibrationCode) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	copy(buf[pos:pos+6], m.Time.Bytes())
	pos += 6

	return buf, nil
}

// UnmarshalBinary decodes TerminalTimeCalibrationCode from binary format (GB1239)
func (m *TerminalTimeCalibrationCode) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+6 > len(data) { return fmt.Errorf("%s: short read", "Time") }
	m.Time, _ = ParseGB1239Time(data[pos:pos+6])
	pos += 6

	return nil
}
// MarshalBinary encodes SignatureInfo to binary format (GB1239)
func (m *SignatureInfo) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	buf[pos] = m.RValueLen
	pos++

	copy(buf[pos:], m.RValue)
	pos += len(m.RValue)

	copy(buf[pos:], m.SValue)
	pos += len(m.SValue)

	return buf, nil
}

// UnmarshalBinary decodes SignatureInfo from binary format (GB1239)
func (m *SignatureInfo) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "RValueLen") }
	m.RValueLen = data[pos]
	pos++

	m.RValue = make([]byte, len(data)-pos)
	copy(m.RValue, data[pos:])
	pos = len(data)

	m.SValue = make([]byte, len(data)-pos)
	copy(m.SValue, data[pos:])
	pos = len(data)

	return nil
}
// MarshalBinary encodes EngineDataDPFSCR to binary format (GB1239)
func (m *EngineDataDPFSCR) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	m.Speed.PutUint16(buf[pos:pos+2], true)
	pos += 2

	m.AtmPressure.PutUint8(buf[pos:pos+1])
	pos++

	m.EngineTorque.PutInt8(buf[pos:pos+1])
	pos++

	m.FrictionTorque.PutInt8(buf[pos:pos+1])
	pos++

	m.EngineSpeed.PutUint16(buf[pos:pos+2], true)
	pos += 2

	m.FuelFlow.PutUint16(buf[pos:pos+2], true)
	pos += 2

	m.SCRUpstreamNOx.PutInt16(buf[pos:pos+2], true)
	pos += 2

	m.SCRDownstreamNOx.PutInt16(buf[pos:pos+2], true)
	pos += 2

	m.ReagentRate.PutUint8(buf[pos:pos+1])
	pos++

	m.AirFlow.PutUint16(buf[pos:pos+2], true)
	pos += 2

	m.SCRUpstreamTemp.PutInt16(buf[pos:pos+2], true)
	pos += 2

	m.SCRDownstreamTemp.PutInt16(buf[pos:pos+2], true)
	pos += 2

	m.DPFDiffPressure.PutUint16(buf[pos:pos+2], true)
	pos += 2

	m.CoolantTemp.PutInt8(buf[pos:pos+1])
	pos++

	m.UreaLevel.PutUint8(buf[pos:pos+1])
	pos++

	buf[pos] = m.PositionStatus
	pos++

	m.Longitude.PutUint32(buf[pos:pos+4], true)
	pos += 4

	m.Latitude.PutUint32(buf[pos:pos+4], true)
	pos += 4

	m.Odometer.PutUint32(buf[pos:pos+4], true)
	pos += 4

	return buf, nil
}

// UnmarshalBinary decodes EngineDataDPFSCR from binary format (GB1239)
func (m *EngineDataDPFSCR) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "Speed") }
	m.Speed.DecodeUint16(data[pos:pos+2], true)
	pos += 2

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "AtmPressure") }
	m.AtmPressure.DecodeUint8(data[pos:pos+1])
	pos++

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "EngineTorque") }
	m.EngineTorque.DecodeInt8(data[pos:pos+1])
	pos++

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "FrictionTorque") }
	m.FrictionTorque.DecodeInt8(data[pos:pos+1])
	pos++

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "EngineSpeed") }
	m.EngineSpeed.DecodeUint16(data[pos:pos+2], true)
	pos += 2

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "FuelFlow") }
	m.FuelFlow.DecodeUint16(data[pos:pos+2], true)
	pos += 2

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "SCRUpstreamNOx") }
	m.SCRUpstreamNOx.DecodeInt16(data[pos:pos+2], true)
	pos += 2

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "SCRDownstreamNOx") }
	m.SCRDownstreamNOx.DecodeInt16(data[pos:pos+2], true)
	pos += 2

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "ReagentRate") }
	m.ReagentRate.DecodeUint8(data[pos:pos+1])
	pos++

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "AirFlow") }
	m.AirFlow.DecodeUint16(data[pos:pos+2], true)
	pos += 2

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "SCRUpstreamTemp") }
	m.SCRUpstreamTemp.DecodeInt16(data[pos:pos+2], true)
	pos += 2

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "SCRDownstreamTemp") }
	m.SCRDownstreamTemp.DecodeInt16(data[pos:pos+2], true)
	pos += 2

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "DPFDiffPressure") }
	m.DPFDiffPressure.DecodeUint16(data[pos:pos+2], true)
	pos += 2

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "CoolantTemp") }
	m.CoolantTemp.DecodeInt8(data[pos:pos+1])
	pos++

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "UreaLevel") }
	m.UreaLevel.DecodeUint8(data[pos:pos+1])
	pos++

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "PositionStatus") }
	m.PositionStatus = data[pos]
	pos++

	if pos+4 > len(data) { return fmt.Errorf("%s: short read", "Longitude") }
	m.Longitude.DecodeUint32(data[pos:pos+4], true)
	pos += 4

	if pos+4 > len(data) { return fmt.Errorf("%s: short read", "Latitude") }
	m.Latitude.DecodeUint32(data[pos:pos+4], true)
	pos += 4

	if pos+4 > len(data) { return fmt.Errorf("%s: short read", "Odometer") }
	m.Odometer.DecodeUint32(data[pos:pos+4], true)
	pos += 4

	return nil
}
// MarshalBinary encodes EngineDataTWC to binary format (GB1239)
func (m *EngineDataTWC) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	m.Speed.PutUint16(buf[pos:pos+2], true)
	pos += 2

	m.AtmPressure.PutUint8(buf[pos:pos+1])
	pos++

	m.EngineTorque.PutInt8(buf[pos:pos+1])
	pos++

	m.FrictionTorque.PutInt8(buf[pos:pos+1])
	pos++

	m.EngineSpeed.PutUint16(buf[pos:pos+2], true)
	pos += 2

	m.FuelFlow.PutUint16(buf[pos:pos+2], true)
	pos += 2

	m.TWCUpstreamO2.PutUint16(buf[pos:pos+2], true)
	pos += 2

	m.TWCUpstreamVoltage.PutUint8(buf[pos:pos+1])
	pos++

	m.AirFlow.PutUint16(buf[pos:pos+2], true)
	pos += 2

	m.CoolantTemp.PutInt8(buf[pos:pos+1])
	pos++

	m.TWCUpstreamTemp.PutInt16(buf[pos:pos+2], true)
	pos += 2

	buf[pos] = m.PositionStatus
	pos++

	m.Longitude.PutUint32(buf[pos:pos+4], true)
	pos += 4

	m.Latitude.PutUint32(buf[pos:pos+4], true)
	pos += 4

	m.Odometer.PutUint32(buf[pos:pos+4], true)
	pos += 4

	return buf, nil
}

// UnmarshalBinary decodes EngineDataTWC from binary format (GB1239)
func (m *EngineDataTWC) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "Speed") }
	m.Speed.DecodeUint16(data[pos:pos+2], true)
	pos += 2

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "AtmPressure") }
	m.AtmPressure.DecodeUint8(data[pos:pos+1])
	pos++

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "EngineTorque") }
	m.EngineTorque.DecodeInt8(data[pos:pos+1])
	pos++

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "FrictionTorque") }
	m.FrictionTorque.DecodeInt8(data[pos:pos+1])
	pos++

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "EngineSpeed") }
	m.EngineSpeed.DecodeUint16(data[pos:pos+2], true)
	pos += 2

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "FuelFlow") }
	m.FuelFlow.DecodeUint16(data[pos:pos+2], true)
	pos += 2

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "TWCUpstreamO2") }
	m.TWCUpstreamO2.DecodeUint16(data[pos:pos+2], true)
	pos += 2

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "TWCUpstreamVoltage") }
	m.TWCUpstreamVoltage.DecodeUint8(data[pos:pos+1])
	pos++

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "AirFlow") }
	m.AirFlow.DecodeUint16(data[pos:pos+2], true)
	pos += 2

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "CoolantTemp") }
	m.CoolantTemp.DecodeInt8(data[pos:pos+1])
	pos++

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "TWCUpstreamTemp") }
	m.TWCUpstreamTemp.DecodeInt16(data[pos:pos+2], true)
	pos += 2

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "PositionStatus") }
	m.PositionStatus = data[pos]
	pos++

	if pos+4 > len(data) { return fmt.Errorf("%s: short read", "Longitude") }
	m.Longitude.DecodeUint32(data[pos:pos+4], true)
	pos += 4

	if pos+4 > len(data) { return fmt.Errorf("%s: short read", "Latitude") }
	m.Latitude.DecodeUint32(data[pos:pos+4], true)
	pos += 4

	if pos+4 > len(data) { return fmt.Errorf("%s: short read", "Odometer") }
	m.Odometer.DecodeUint32(data[pos:pos+4], true)
	pos += 4

	return nil
}
// MarshalBinary encodes EngineDataTWCNOx to binary format (GB1239)
func (m *EngineDataTWCNOx) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	m.Speed.PutUint16(buf[pos:pos+2], true)
	pos += 2

	m.AtmPressure.PutUint8(buf[pos:pos+1])
	pos++

	m.EngineTorque.PutInt8(buf[pos:pos+1])
	pos++

	m.FrictionTorque.PutInt8(buf[pos:pos+1])
	pos++

	m.EngineSpeed.PutUint16(buf[pos:pos+2], true)
	pos += 2

	m.FuelFlow.PutUint16(buf[pos:pos+2], true)
	pos += 2

	m.TWCUpstreamO2.PutUint16(buf[pos:pos+2], true)
	pos += 2

	m.TWCUpstreamVoltage.PutUint8(buf[pos:pos+1])
	pos++

	m.NOxUpstream.PutInt16(buf[pos:pos+2], true)
	pos += 2

	m.AirFlow.PutUint16(buf[pos:pos+2], true)
	pos += 2

	m.CoolantTemp.PutInt8(buf[pos:pos+1])
	pos++

	m.SensorTemp.PutInt16(buf[pos:pos+2], true)
	pos += 2

	buf[pos] = m.PositionStatus
	pos++

	m.Longitude.PutUint32(buf[pos:pos+4], true)
	pos += 4

	m.Latitude.PutUint32(buf[pos:pos+4], true)
	pos += 4

	m.Odometer.PutUint32(buf[pos:pos+4], true)
	pos += 4

	return buf, nil
}

// UnmarshalBinary decodes EngineDataTWCNOx from binary format (GB1239)
func (m *EngineDataTWCNOx) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "Speed") }
	m.Speed.DecodeUint16(data[pos:pos+2], true)
	pos += 2

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "AtmPressure") }
	m.AtmPressure.DecodeUint8(data[pos:pos+1])
	pos++

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "EngineTorque") }
	m.EngineTorque.DecodeInt8(data[pos:pos+1])
	pos++

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "FrictionTorque") }
	m.FrictionTorque.DecodeInt8(data[pos:pos+1])
	pos++

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "EngineSpeed") }
	m.EngineSpeed.DecodeUint16(data[pos:pos+2], true)
	pos += 2

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "FuelFlow") }
	m.FuelFlow.DecodeUint16(data[pos:pos+2], true)
	pos += 2

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "TWCUpstreamO2") }
	m.TWCUpstreamO2.DecodeUint16(data[pos:pos+2], true)
	pos += 2

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "TWCUpstreamVoltage") }
	m.TWCUpstreamVoltage.DecodeUint8(data[pos:pos+1])
	pos++

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "NOxUpstream") }
	m.NOxUpstream.DecodeInt16(data[pos:pos+2], true)
	pos += 2

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "AirFlow") }
	m.AirFlow.DecodeUint16(data[pos:pos+2], true)
	pos += 2

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "CoolantTemp") }
	m.CoolantTemp.DecodeInt8(data[pos:pos+1])
	pos++

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "SensorTemp") }
	m.SensorTemp.DecodeInt16(data[pos:pos+2], true)
	pos += 2

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "PositionStatus") }
	m.PositionStatus = data[pos]
	pos++

	if pos+4 > len(data) { return fmt.Errorf("%s: short read", "Longitude") }
	m.Longitude.DecodeUint32(data[pos:pos+4], true)
	pos += 4

	if pos+4 > len(data) { return fmt.Errorf("%s: short read", "Latitude") }
	m.Latitude.DecodeUint32(data[pos:pos+4], true)
	pos += 4

	if pos+4 > len(data) { return fmt.Errorf("%s: short read", "Odometer") }
	m.Odometer.DecodeUint32(data[pos:pos+4], true)
	pos += 4

	return nil
}
// MarshalBinary encodes EngineDataHybrid to binary format (GB1239)
func (m *EngineDataHybrid) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	m.MotorSpeed.PutUint16(buf[pos:pos+2], true)
	pos += 2

	m.PowerPercent.PutUint8(buf[pos:pos+1])
	pos++

	m.BatteryVoltage.PutUint16(buf[pos:pos+2], true)
	pos += 2

	m.BatteryCurrent.PutInt16(buf[pos:pos+2], true)
	pos += 2

	m.BatterySOC.PutUint8(buf[pos:pos+1])
	pos++

	return buf, nil
}

// UnmarshalBinary decodes EngineDataHybrid from binary format (GB1239)
func (m *EngineDataHybrid) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "MotorSpeed") }
	m.MotorSpeed.DecodeUint16(data[pos:pos+2], true)
	pos += 2

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "PowerPercent") }
	m.PowerPercent.DecodeUint8(data[pos:pos+1])
	pos++

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "BatteryVoltage") }
	m.BatteryVoltage.DecodeUint16(data[pos:pos+2], true)
	pos += 2

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "BatteryCurrent") }
	m.BatteryCurrent.DecodeInt16(data[pos:pos+2], true)
	pos += 2

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "BatterySOC") }
	m.BatterySOC.DecodeUint8(data[pos:pos+1])
	pos++

	return nil
}
// MarshalBinary encodes VehicleStatus to binary format (GB1239)
func (m *VehicleStatus) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.MilStatus)
	pos += 2

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.DiagSupportStatus)
	pos += 2

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.DiagCompleteStatus)
	pos += 2

	copy(buf[pos:pos+17], []byte(m.VIN))
	pos += 17

	copy(buf[pos:], []byte(m.CalibrationID))
	pos += len(m.CalibrationID)

	copy(buf[pos:], []byte(m.CVN))
	pos += len(m.CVN)

	copy(buf[pos:pos+36], []byte(m.IUPR))
	pos += 36

	buf[pos] = m.DTCCount
	pos++

	copy(buf[pos:], m.DTCCodes)
	pos += len(m.DTCCodes)

	return buf, nil
}

// UnmarshalBinary decodes VehicleStatus from binary format (GB1239)
func (m *VehicleStatus) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "MilStatus") }
	m.MilStatus = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "DiagSupportStatus") }
	m.DiagSupportStatus = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "DiagCompleteStatus") }
	m.DiagCompleteStatus = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	if pos+17 > len(data) { return fmt.Errorf("%s: short read", "VIN") }
	m.VIN = string(data[pos:pos+17])
	pos += 17

	m.CalibrationID = string(data[pos:])
	pos = len(data)

	m.CVN = string(data[pos:])
	pos = len(data)

	if pos+36 > len(data) { return fmt.Errorf("%s: short read", "IUPR") }
	m.IUPR = string(data[pos:pos+36])
	pos += 36

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "DTCCount") }
	m.DTCCount = data[pos]
	pos++

	m.DTCCodes = make([]byte, len(data)-pos)
	copy(m.DTCCodes, data[pos:])
	pos = len(data)

	return nil
}
// MarshalBinary encodes RealTimeInfoBlock to binary format (GB1239)
func (m *RealTimeInfoBlock) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	buf[pos] = m.InfoTypeFlag
	pos++

	copy(buf[pos:pos+6], m.CollectTime.Bytes())
	pos += 6

	// TODO: encode InfoBody (type *ast.InterfaceType)

	return buf, nil
}

// UnmarshalBinary decodes RealTimeInfoBlock from binary format (GB1239)
func (m *RealTimeInfoBlock) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "InfoTypeFlag") }
	m.InfoTypeFlag = data[pos]
	pos++

	if pos+6 > len(data) { return fmt.Errorf("%s: short read", "CollectTime") }
	m.CollectTime, _ = ParseGB1239Time(data[pos:pos+6])
	pos += 6

	// TODO: decode InfoBody (type *ast.InterfaceType)

	return nil
}
// MarshalBinary encodes RealTimeInfoReport to binary format (GB1239)
func (m *RealTimeInfoReport) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	copy(buf[pos:pos+6], m.DataTime.Bytes())
	pos += 6

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.SerialNum)
	pos += 2

	// TODO: encode InfoBlocks (type []RealTimeInfoBlock)

	// TODO: encode SignatureInfo (type *SignatureInfo)

	return buf, nil
}

// UnmarshalBinary decodes RealTimeInfoReport from binary format (GB1239)
func (m *RealTimeInfoReport) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+6 > len(data) { return fmt.Errorf("%s: short read", "DataTime") }
	m.DataTime, _ = ParseGB1239Time(data[pos:pos+6])
	pos += 6

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "SerialNum") }
	m.SerialNum = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	// TODO: decode InfoBlocks (type []RealTimeInfoBlock)

	m.SignatureInfo = &SignatureInfo{}
	if err := m.SignatureInfo.Decode(data[pos:]); err != nil { return err }
	pos += m.SignatureInfo.Size()

	return nil
}
// MarshalBinary encodes VehicleInfoCode to binary format (GB1239)
func (m *VehicleInfoCode) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	copy(buf[pos:pos+6], m.CollectTime.Bytes())
	pos += 6

	copy(buf[pos:pos+16], []byte(m.ChipID))
	pos += 16

	copy(buf[pos:pos+64], []byte(m.Key))
	pos += 64

	copy(buf[pos:pos+17], []byte(m.VIN))
	pos += 17

	copy(buf[pos:], []byte(m.Signature))
	pos += len(m.Signature)

	return buf, nil
}

// UnmarshalBinary decodes VehicleInfoCode from binary format (GB1239)
func (m *VehicleInfoCode) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+6 > len(data) { return fmt.Errorf("%s: short read", "CollectTime") }
	m.CollectTime, _ = ParseGB1239Time(data[pos:pos+6])
	pos += 6

	if pos+16 > len(data) { return fmt.Errorf("%s: short read", "ChipID") }
	m.ChipID = string(data[pos:pos+16])
	pos += 16

	if pos+64 > len(data) { return fmt.Errorf("%s: short read", "Key") }
	m.Key = string(data[pos:pos+64])
	pos += 64

	if pos+17 > len(data) { return fmt.Errorf("%s: short read", "VIN") }
	m.VIN = string(data[pos:pos+17])
	pos += 17

	m.Signature = string(data[pos:])
	pos = len(data)

	return nil
}
// MarshalBinary encodes VehicleInfoResponseCode to binary format (GB1239)
func (m *VehicleInfoResponseCode) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	buf[pos] = m.Status
	pos++

	buf[pos] = m.Message
	pos++

	return buf, nil
}

// UnmarshalBinary decodes VehicleInfoResponseCode from binary format (GB1239)
func (m *VehicleInfoResponseCode) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "Status") }
	m.Status = data[pos]
	pos++

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "Message") }
	m.Message = data[pos]
	pos++

	return nil
}
// MarshalBinary encodes TerminalSupplementCode to binary format (GB1239)
func (m *TerminalSupplementCode) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	copy(buf[pos:pos+6], m.CollectTime.Bytes())
	pos += 6

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.SerialNum)
	pos += 2

	buf[pos] = m.PositionStatus
	pos++

	m.Longitude.PutUint32(buf[pos:pos+4], true)
	pos += 4

	m.Latitude.PutUint32(buf[pos:pos+4], true)
	pos += 4

	return buf, nil
}

// UnmarshalBinary decodes TerminalSupplementCode from binary format (GB1239)
func (m *TerminalSupplementCode) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+6 > len(data) { return fmt.Errorf("%s: short read", "CollectTime") }
	m.CollectTime, _ = ParseGB1239Time(data[pos:pos+6])
	pos += 6

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "SerialNum") }
	m.SerialNum = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "PositionStatus") }
	m.PositionStatus = data[pos]
	pos++

	if pos+4 > len(data) { return fmt.Errorf("%s: short read", "Longitude") }
	m.Longitude.DecodeUint32(data[pos:pos+4], true)
	pos += 4

	if pos+4 > len(data) { return fmt.Errorf("%s: short read", "Latitude") }
	m.Latitude.DecodeUint32(data[pos:pos+4], true)
	pos += 4

	return nil
}
// MarshalBinary encodes OBDInfoBody to binary format (GB1239)
func (m *OBDInfoBody) MarshalBinary() ([]byte, error) {
	totalSize := m.Size()
	buf := make([]byte, totalSize)
	pos := 0

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.MilStatus)
	pos += 2

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.DiagSupportStatus)
	pos += 2

	binary.BigEndian.PutUint16(buf[pos:pos+2], m.DiagCompleteStatus)
	pos += 2

	copy(buf[pos:pos+17], []byte(m.VIN))
	pos += 17

	copy(buf[pos:pos+18], []byte(m.CalibrationID))
	pos += 18

	copy(buf[pos:pos+18], []byte(m.CVN))
	pos += 18

	copy(buf[pos:pos+36], []byte(m.IUPR))
	pos += 36

	buf[pos] = m.DTCCount
	pos++

	copy(buf[pos:], m.DTCCodes)
	pos += len(m.DTCCodes)

	return buf, nil
}

// UnmarshalBinary decodes OBDInfoBody from binary format (GB1239)
func (m *OBDInfoBody) UnmarshalBinary(data []byte) error {
	pos := 0

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "MilStatus") }
	m.MilStatus = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "DiagSupportStatus") }
	m.DiagSupportStatus = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	if pos+2 > len(data) { return fmt.Errorf("%s: short read", "DiagCompleteStatus") }
	m.DiagCompleteStatus = binary.BigEndian.Uint16(data[pos:pos+2])
	pos += 2

	if pos+17 > len(data) { return fmt.Errorf("%s: short read", "VIN") }
	m.VIN = string(data[pos:pos+17])
	pos += 17

	if pos+18 > len(data) { return fmt.Errorf("%s: short read", "CalibrationID") }
	m.CalibrationID = string(data[pos:pos+18])
	pos += 18

	if pos+18 > len(data) { return fmt.Errorf("%s: short read", "CVN") }
	m.CVN = string(data[pos:pos+18])
	pos += 18

	if pos+36 > len(data) { return fmt.Errorf("%s: short read", "IUPR") }
	m.IUPR = string(data[pos:pos+36])
	pos += 36

	if pos+1 > len(data) { return fmt.Errorf("%s: short read", "DTCCount") }
	m.DTCCount = data[pos]
	pos++

	m.DTCCodes = make([]byte, len(data)-pos)
	copy(m.DTCCodes, data[pos:])
	pos = len(data)

	return nil
}
